title: Hyunsang Park
description: Autonomy will define the next generation of aerospace. My goal is to find solutions that can provide resilience and optimality for uncertain systems without human intervention.
logo: logo.jpg
theme: jekyll-theme-minimal



