title: Hyunsang Park
description: Autonomy will define the next generation of aerospace. My goal is to find solutions that can guarantee resilience and safety in unknown/uncertain systems without human intervention.
logo: logo.jpg
theme: jekyll-theme-minimal



